apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: late-locust-java-springboot 
  janus-idp.io/tekton: late-locust-java-springboot
  backstage.io/kubernetes-id: late-locust-java-springboot
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: late-locust-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  